apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticwebapp-deployment
  namespace: dev-ci-cd
  labels:
    app: staticwebapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: staticwebapp
  template:
    metadata:
      labels:
        app: staticwebapp
    spec:
      containers:
      - name: staticwebapp
        image: nnorman062/staticweb:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: staticwebapp
  namespace: dev-ci-cd
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: staticwebapp
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: staticweb-ingress
  namespace: dev-ci-cd
spec:
  rules:
  - host: "test-staticweb.nnorman.tech"
    http:
      paths:
      - backend:
          serviceName: staticwebapp
          servicePort: 80
